version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:resolve
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn test
      - store_test_results:
          path: target/surefire-reports
      - run: mvn jacoco:prepare-agent install jacoco:report
      - store_artifacts:
          path: target/site/jacoco
  create_github_tag:
    docker:
      - image: cimg/base:2023.09
    steps:
      - checkout
      - run:
          name: Create GitHub Tag
          command: |
            if [ -n "$CIRCLE_TAG" ]; then
              echo "Skipping tag creation as this is already a tagged build."
            else
              NEW_TAG="v1.0.${CIRCLE_BUILD_NUM}"
              git config user.email "circleci@example.com"
              git config user.name "CircleCI"
              git tag $NEW_TAG
              git push https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git $NEW_TAG
              echo "Created GitHub tag: $NEW_TAG"
            fi

workflows:
  build_test_and_tag:
    jobs:
      - build_and_test
      - create_github_tag:
          requires:
            - build_and_test
          filters:
            branches:
              only: main
            tags:
              ignore: /.*/
